### ISSUE TITLE
Bundle failing at UMD step.

### ISSUE THREAD

**Issue by ashleahhill** [danielberndt/db-scripts#1]
```
[umd.min]     `sourcemap` is not a supported option
[umd.min]
[umd.min] [!] (terser plugin) Error: `sourcemap` is not a supported option
[umd.min] DefaultsError: `sourcemap` is not a supported option
```

Running `db-scripts-bundle --size-snapshot` on a a single `index.js` file.

I think the issue has to do with rollup-plugin-terser, since it's only failing at the `umd.min` part. but its the dep of webpack that's actually updated:

![Screen Shot 2019-09-03 at 6 16 02 PM](https://user-images.githubusercontent.com/1854792/64212299-ea11ab00-ce76-11e9-8c10-03bd06381d83.png)

**Comment by danielberndt** [comment]
Thanks for reporting. Eventually got around to updating the dependencies. Should be fixed now!
